// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	model "expense-management-system/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// PaymentPartnerRepository is an autogenerated mock type for the PaymentPartnerRepository type
type PaymentPartnerRepository struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, req
func (_m *PaymentPartnerRepository) Execute(ctx context.Context, req *model.PaymentPartnerRequest) (*model.PaymentPartnerResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *model.PaymentPartnerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.PaymentPartnerRequest) (*model.PaymentPartnerResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.PaymentPartnerRequest) *model.PaymentPartnerResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PaymentPartnerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.PaymentPartnerRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentPartnerRepository creates a new instance of PaymentPartnerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentPartnerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentPartnerRepository {
	mock := &PaymentPartnerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
